### ISSUE TITLE
Host en webapplikation 

### ISSUE THREAD

**Issue by KjartanLeander** [Kaptajnerne/EksamensProjekt#1]

**Comment by LilNiclas** [comment]
Build Image - Done
Build Container - Done
Get Local Address to port - Error 500 = Access denied for user 'root'@'127.0.0.1' (using password: YES)

**Comment by lakruzz** [comment]
@LilNiclas @KjartanLeander @SimonBD1 @tobiasbkraemer 

Den fejl I får på render:

```
Access denied for user 'root'@'127.0.0.1' (using password: YES)] 
```
Hænger sammen med at I slet ikke har fået sat password på den instans som kørere i skyen!

Når I tester den lokalt starter I den [sådan her](https://github.com/Kaptajnerne/EksamensProjekt/blob/c88dcb0d2accbe8979f2307d7a12f2faf291bb00/Dockerfile#L29)

Password skal matche det som [står i jeres application.properties](https://github.com/Kaptajnerne/EksamensProjekt/blob/c88dcb0d2accbe8979f2307d7a12f2faf291bb00/src/main/resources/application.properties#L3)

Når vi bare starter applikationen på Render og ikke sætter et password, så er det "root" (...det kommer fra [`lakruzz/lamj` containeren](https://github.com/kea-dev/lamj/blob/eb8bfea25962dbf856c3194ed660fa46ed257d7b/dockerfile#L11)).

I skal sætte det på Render som en _shared secret_

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/155492/234064311-821c2784-e778-4f7b-95e1-2d1f238126cf.png">

...så kører det for jer!

**Comment by LilNiclas** [comment]
@lakruzz 

Jeg gav det lige et forsøg, og problemet var som du sagde.

Nu er der kontakt til databasen og det hele er oppe at køre!

![Billede af webapplikation, webapplikation er opsat vha. Render](https://user-images.githubusercontent.com/113116068/234364559-059563df-85f0-4f0f-bae7-375ae4df12bb.png)

**Mange tak for hjælpen:)**
