### ISSUE TITLE
As a user I want to be able to view a project as a GANTT chart

### ISSUE THREAD

**Issue by KjartanLeander** [Kaptajnerne/EksamensProjekt#47]
<h3>User enter page with a gantt chart showing all task and subtask from a project</h3>

**Comment by KjartanLeander** [comment]
GANTT chart is shown on site

**Comment by LilNiclas** [comment]
Hej @lakruzz 
Jeg har prøvet at lave et gantt chart vha. google charts de sidste par dage, og støder på nogen problemer. 
Helt specfikt så kan jeg ikke få adgang til et field(_year_) i min LocalDate pga. module restriktioner.
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final int java.time.LocalDate.year accessible: module java.base does not "opens java.time" to unnamed module @6302bbb1
```

Jeg har prøvet at lave en jar fil og give adgang: ``` --add-opens  java.base/java.time=ALL-UNNAMED -jar EksamensProjekt.jar ``` Men har stadig samme problem. Kunne måske også være min version af Java ikke er kompatible med mine libraries og frameworks.

Så ville høre hvilke dage du var på KEA, så jeg måske kunne få en hånd at få det løst


_Udarbejdet på **GanttDiagram** branch_

**Comment by lakruzz** [comment]
@LilNiclas Hmm - jeg har ikke så meget mere at gå efter end det du selv har googlet ([f.eks.](https://www.springcloud.io/post/2022-07/inaccessibleobjectexception/#gsc.tab=0))

Fandt også [den her](https://stackoverflow.com/questions/70412805/what-does-this-error-mean-java-lang-reflect-inaccessibleobjectexception-unable/75250722#75250722) - som ligner en anden vej.

Ellers skal du måske ha' nogle Java experter på banene: Tine eller Mads 🤔
